version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosq-cloud
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - mosq_data:/mosquitto/data
volumes:
  mosq_data: